name = "verazadoptantes2"
compatibility_date = "2025-01-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "pet-adoption-db"
database_id = "62ec01e7-deae-4536-be62-7c0a0064b45c"
migrations_dir = "drizzle"

[vars]
EMAIL_FROM = "noreply@buenadoptante.org"
# AUTH_URL is vital for NextAuth in prod. Update this if your custom domain differs.
AUTH_URL = "https://buenadoptante.org"
# Note: AXIOM_DATASET and AXIOM_TOKEN are configured in Cloudflare Pages dashboard
