name = "verazadoptantes2"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "pet-adoption-db"
database_id = "62ec01e7-deae-4536-be62-7c0a0064b45c"
