-- [BROKEN] Original had literal \r\n text instead of real newlines.
-- D1 recorded this as applied but the ALTER TABLE never executed.
-- Actual column creation is handled by 0032_repair_notification_dismissed.sql
