/**
 * iOS PWA launch images (apple-touch-startup-image). Without these, an installed
 * PWA on iOS shows a blank background-colored screen on cold start. Generated by
 * scripts/gen-splash.js (brand-teal ground + white shield-paw logo + wordmark),
 * one per common iPhone/iPad portrait size. Portrait only — the manifest is
 * portrait-primary. Regenerate with `node scripts/gen-splash.js` if the logo or
 * device list changes.
 */
export default function AppleSplashLinks() {
    const SPLASH: Array<{ w: number; h: number; dw: number; dh: number; r: number }> = [
        { w: 640, h: 1136, dw: 320, dh: 568, r: 2 },
        { w: 750, h: 1334, dw: 375, dh: 667, r: 2 },
        { w: 1242, h: 2208, dw: 414, dh: 736, r: 3 },
        { w: 1125, h: 2436, dw: 375, dh: 812, r: 3 },
        { w: 828, h: 1792, dw: 414, dh: 896, r: 2 },
        { w: 1242, h: 2688, dw: 414, dh: 896, r: 3 },
        { w: 1170, h: 2532, dw: 390, dh: 844, r: 3 },
        { w: 1284, h: 2778, dw: 428, dh: 926, r: 3 },
        { w: 1179, h: 2556, dw: 393, dh: 852, r: 3 },
        { w: 1290, h: 2796, dw: 430, dh: 932, r: 3 },
        { w: 1536, h: 2048, dw: 768, dh: 1024, r: 2 },
        { w: 1620, h: 2160, dw: 810, dh: 1080, r: 2 },
        { w: 1668, h: 2224, dw: 834, dh: 1112, r: 2 },
        { w: 1668, h: 2388, dw: 834, dh: 1194, r: 2 },
        { w: 2048, h: 2732, dw: 1024, dh: 1366, r: 2 },
    ];
    return (
        <>
            {SPLASH.map(({ w, h, dw, dh, r }) => (
                <link
                    key={`${w}x${h}`}
                    rel="apple-touch-startup-image"
                    href={`/splash/apple-splash-${w}x${h}.png`}
                    media={`(device-width: ${dw}px) and (device-height: ${dh}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait)`}
                />
            ))}
        </>
    );
}
